[2024-04-30T22:12:50.582-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T22:12:50.641-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.path_does_not_exist manual__2024-05-01T01:11:28.778130+00:00 [queued]>
[2024-04-30T22:12:50.654-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.path_does_not_exist manual__2024-05-01T01:11:28.778130+00:00 [queued]>
[2024-04-30T22:12:50.654-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T22:12:51.017-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): path_does_not_exist> on 2024-05-01 01:11:28.778130+00:00
[2024-04-30T22:12:51.023-0300] {standard_task_runner.py:63} INFO - Started process 37077 to run task
[2024-04-30T22:12:51.047-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'path_does_not_exist', 'manual__2024-05-01T01:11:28.778130+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmphco3ske3']
[2024-04-30T22:12:51.048-0300] {standard_task_runner.py:91} INFO - Job 69: Subtask path_does_not_exist
[2024-04-30T22:12:51.490-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.path_does_not_exist manual__2024-05-01T01:11:28.778130+00:00 [running]> on host xubuntu.myguest.virtualbox.org
[2024-04-30T22:12:52.383-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='path_does_not_exist' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T01:11:28.778130+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T01:11:28.778130+00:00'
[2024-04-30T22:12:52.421-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T22:12:52.422-0300] {logging_mixin.py:188} INFO - Ocorreu um erro ao tentar recuperar o caminho da vari√°vel de ambiente AIRFLOW_HOME
[2024-04-30T22:12:52.423-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T22:12:52.423-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T22:12:53.154-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=atividade_pratica_dag, task_id=path_does_not_exist, execution_date=20240501T011128, start_date=20240501T011250, end_date=20240501T011253
[2024-04-30T22:12:53.702-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T22:12:53.779-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T22:12:53.783-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
