[2024-04-28T20:52:25.893-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T20:52:25.916-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.get_path manual__2024-04-28T23:52:05.365467+00:00 [queued]>
[2024-04-28T20:52:25.927-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.get_path manual__2024-04-28T23:52:05.365467+00:00 [queued]>
[2024-04-28T20:52:25.927-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T20:52:25.954-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): get_path> on 2024-04-28 23:52:05.365467+00:00
[2024-04-28T20:52:25.960-0300] {standard_task_runner.py:63} INFO - Started process 10022 to run task
[2024-04-28T20:52:25.965-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'get_path', 'manual__2024-04-28T23:52:05.365467+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmpeoh1lzth']
[2024-04-28T20:52:25.966-0300] {standard_task_runner.py:91} INFO - Job 13: Subtask get_path
[2024-04-28T20:52:26.011-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.get_path manual__2024-04-28T23:52:05.365467+00:00 [running]> on host ath
[2024-04-28T20:52:26.095-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='get_path' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T23:52:05.365467+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-28T23:52:05.365467+00:00'
[2024-04-28T20:52:26.097-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T20:52:26.098-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-28T20:52:26.099-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo $AIRFLOW_HOME  > data/path.txt']
[2024-04-28T20:52:26.119-0300] {subprocess.py:86} INFO - Output:
[2024-04-28T20:52:26.123-0300] {subprocess.py:93} INFO - /usr/bin/bash: linha 1: data/path.txt: Arquivo ou diret√≥rio inexistente
[2024-04-28T20:52:26.124-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-28T20:52:26.125-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T20:52:26.145-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-28T20:52:26.154-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica_dag, task_id=get_path, execution_date=20240428T235205, start_date=20240428T235225, end_date=20240428T235226
[2024-04-28T20:52:26.441-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task get_path (Bash command failed. The command returned a non-zero exit code 1.; 10022)
[2024-04-28T20:52:26.497-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T20:52:26.526-0300] {logging_mixin.py:188} WARNING - /home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-28T20:52:26.550-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T20:52:26.559-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
