[2024-04-30T19:20:18.043-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T19:20:18.074-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_file_dag.check_file_empty manual__2024-04-30T22:19:39.471143+00:00 [queued]>
[2024-04-30T19:20:18.088-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_file_dag.check_file_empty manual__2024-04-30T22:19:39.471143+00:00 [queued]>
[2024-04-30T19:20:18.089-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T19:20:18.126-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_file_empty> on 2024-04-30 22:19:39.471143+00:00
[2024-04-30T19:20:18.146-0300] {standard_task_runner.py:63} INFO - Started process 26912 to run task
[2024-04-30T19:20:18.184-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'check_file_dag', 'check_file_empty', 'manual__2024-04-30T22:19:39.471143+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/file_sensor_dag.py', '--cfg-path', '/tmp/tmpdewepj2n']
[2024-04-30T19:20:18.186-0300] {standard_task_runner.py:91} INFO - Job 62: Subtask check_file_empty
[2024-04-30T19:20:18.394-0300] {task_command.py:426} INFO - Running <TaskInstance: check_file_dag.check_file_empty manual__2024-04-30T22:19:39.471143+00:00 [running]> on host xubuntu.myguest.virtualbox.org
[2024-04-30T19:20:18.619-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='check_file_dag' AIRFLOW_CTX_TASK_ID='check_file_empty' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T22:19:39.471143+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T22:19:39.471143+00:00'
[2024-04-30T19:20:18.621-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T19:20:18.624-0300] {logging_mixin.py:188} INFO - O arquivo /home/ath/projects/atividade_pratica_dags/dags/ls_dag.py não está vazio.
[2024-04-30T19:20:18.625-0300] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T19:20:18.625-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T19:20:18.629-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=check_file_dag, task_id=check_file_empty, execution_date=20240430T221939, start_date=20240430T222018, end_date=20240430T222018
[2024-04-30T19:20:18.707-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T19:20:18.723-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T19:20:18.724-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
